<h1><strong>Welcome to Week 2</strong> </h1>
<p>This notebook will teach you the basics of the Python programming language. Although the information presented here is quite basic, it is an important foundation that will help you read and write Python code. By the end of this notebook, you'll know the basics of Python.</p>

# <h2 id="types_objects">Types of objects in Python</h2>

<p>Python is an object-oriented language. There are many different types of objects in Python. Let's start with the most common object types: <i>strings</i>, <i>integers</i> and <i>floats</i>. Anytime you write words (text) in Python, you're using <i>character strings</i> (strings for short). The most common numbers, on the other hand, are <i>integers</i> (e.g. -1, 0, 100) and <i>floats</i>, which represent real numbers (e.g. 3.14, -42.0).</p>

<a align="center">
    <img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/Chapter%201/Images/TypesObjects.png" width="600">
</a>

<p>The following code cells contain some examples.</p>

In [1]:
# Integer

11

11

In [2]:
# Float

2.14

2.14

In [7]:
# String

"Hello, Python 101!"
#"Hello, Python 101!"

'Hello, Python 101!'

<p>You can get Python to tell you the type of an expression by using the built-in <code>type()</code> function. You'll notice that Python refers to integers as <code>int</code>, floats as <code>float</code>, and character strings as <code>str</code>.</p>

In [8]:
# Type of 12

type(12)

int

In [9]:
# Type of 2.14

type(2.14)

float

In [10]:
# Type of "Hello, Python 101!"

type("Hello, Python 101!")

str

<p>In the code cell below, use the <code>type()</code> function to check the object type of <code>12.0</code>.

In [11]:
# Write your code below. Don't forget to press Shift+Enter to execute the cell
type(12.0)

float

Double-click __here__ for the solution.

<!-- Your answer is below:

type(12.0)

-->

## <h3 id="int">Integers</h3>

<p>Here are some examples of integers. Integers can be negative or positive numbers:</p>

<a align="center">
    <img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/Chapter%201/Images/TypesInt.png" width="600">
</a>

<p>We can verify this is the case by using, you guessed it, the <code>type()</code> function:

In [12]:
# Print the type of -1

type(-1)

int

In [13]:
type (-6)

int

In [14]:
# Print the type of 4

type(4)

int

In [15]:
# Print the type of 0

type(0)

int

## <h3 id="float">Floats</h3>

<p>Floats represent real numbers; they are a superset of integer numbers but also include "numbers with decimals". There are some limitations when it comes to machines representing real numbers, but floating point numbers are a good representation in most cases. You can learn more about the specifics of floats for your runtime environment, by checking the value of <code>sys.float_info</code>. This will also tell you what's the largest and smallest number that can be represented with them.</p>

<p>Once again, can test some examples with the <code>type()</code> function:

In [16]:
# Print the type of 1.0

type(1.0) # Notice that 1 is an int, and 1.0 is a float

float

In [17]:
# Print the type of 0.5

type(0.5)

float

In [18]:
# Print the type of 0.56

type(0.56)

float

In [19]:
# System settings about float type
import sys # it is needes to declare the library "sys" before using it
sys.float_info

sys.float_info(max=1.7976931348623157e+308, max_exp=1024, max_10_exp=308, min=2.2250738585072014e-308, min_exp=-1021, min_10_exp=-307, dig=15, mant_dig=53, epsilon=2.220446049250313e-16, radix=2, rounds=1)

## <h3 id="convert">Converting from one object type to a different object type</h3>

<p>You can change the type of the object in Python; this is called typecasting. For example, you can convert an <i>integer</i> into a <i>float</i> (e.g. 2 to 2.0).</p>
<p>Let's try it:</p>

In [20]:
# Verify that this is an integer

type(2)

int

### <h4>Converting integers to floats</h4>
<p>Let's cast integer 2 to float:</p>

In [21]:
# Convert 2 to a float

float(2)

2.0

In [22]:
# Convert integer 2 to a float and check its type

type(float(2))

float

<p>When we convert an integer into a float, we don't really change the value (i.e., the significand) of the number. However, if we cast a float into an integer, we could potentially lose some information. For example, if we cast the float 1.1 to integer we will get 1 and lose the decimal information (i.e., 0.1):</p>

In [26]:
# Casting 1.1 to integer will result in loss of information

int(1.1)

1

### <h4>Converting from strings to integers or floats</h4>

<p>Sometimes, we can have a string that contains a number within it. If this is the case, we can cast that string that represents a number into an integer using <code>int()</code>:</p>

In [27]:
# Convert a string into an integer

int('1')
int('6')

6

<p>But if you try to do so with a string that is not a perfect match for a number, you'll get an error. Try the following:</p>

In [28]:
# Convert a string into an integer with error

int('1 or 2 people')

ValueError: ignored

<p>You can also convert strings containing floating point numbers into <i>float</i> objects:</p>

In [32]:
# Convert the string "1.2" into a float

float('1.2')

1.2

<hr/>
<div class="alert alert-success alertsuccess" style="margin-top: 20px">
    [Tip:] Note that strings can be represented with single quotes (<code>'1.2'</code>) or double quotes (<code>"1.2"</code>), but you can't mix both (e.g., <code>"1.2'</code>).
</div>
<hr/>

### <h4>Converting numbers to strings</h4>

<p>If we can convert strings to numbers, it is only natural to assume that we can convert numbers to strings, right?</p>

In [33]:
# Convert an integer to a string

str(1)

'1'

<p>And there is no reason why we shouldn't be able to make floats into strings as well:</p>

In [34]:
# Convert a float to a string

str(1.2)

'1.2'

## <h3 id="bool">Boolean data type</h3>

<p><i>Boolean</i> is another important type in Python. An object of type <i>Boolean</i> can take on one of two values: <code>True</code> or <code>False</code>:</p>

In [35]:
# Value true

True

True

<p>Notice that the value <code>True</code> has an uppercase "T". The same is true for <code>False</code> (i.e. you must use the uppercase "F").</p>

In [36]:
# Value false

False

False

<p>When you ask Python to display the type of a boolean object it will show <code>bool</code> which stands for <i>boolean</i>:</p>

In [37]:
# Type of True

type(True)

bool

In [38]:
# Type of False

type(False)

bool

<p>We can cast boolean objects to other data types. If we cast a boolean with a value of <code>True</code> to an integer or float we will get a one. If we cast a boolean with a value of <code>False</code> to an integer or float we will get a zero. Similarly, if we cast a 1 to a Boolean, you get a <code>True</code>. And if we cast a 0 to a Boolean we will get a <code>False</code>. Let's give it a try:</p>

In [39]:
# Convert True to int

int(True)

1

In [40]:
# Convert 1 to boolean

bool(1)

True

In [41]:
# Convert 0 to boolean

bool(0)

False

In [42]:
# Convert True to float

float(True)

1.0

## <h3 id="exer_type">Exercise: Types</h3>

<p>What is the data type of the result of: <code>6 / 2</code>?</p>

In [43]:
# Write your code below. Don't forget to press Shift+Enter to execute the cell
type(6/2)

float

Double-click __here__ for the solution.

<!-- Your answer is below:
type(6/2) # float
-->

<p>What is the type of the result of: <code>6 // 2</code>? (Note the double slash <code>//</code>.)</p>

In [44]:
# Write your code below. Don't forget to press Shift+Enter to execute the cell
type(6//2)

int

Double-click __here__ for the solution.

<!-- Your answer is below:
type(6//2) # int, as the double slashes stand for integer division
-->

<hr>

# <h2 id="expressions">Expression and Variables</h2>

<h3 id="exp">Expressions</h3>

<p>Expressions in Python can include operations among compatible types (e.g., integers and floats). For example, basic arithmetic operations like adding multiple numbers:</p>

In [46]:
# Addition operation expression

43 + 60 + 16 + 41

type(10.55+10.5-5)

float

<p>We can perform subtraction operations using the minus operator. In this case the result is a negative number:</p>

In [47]:
# Subtraction operation expression

type(50 - 60)

int

<p>We can do multiplication using an asterisk:</p>

In [48]:
# Multiplication operation expression

5 * 5

25

<p>We can also perform division with the forward slash:

In [49]:
# Division operation expression

25 / 5

5.0

In [50]:
# Division operation expression

25 / 6

4.166666666666667

<p>As seen in the quiz above, we can use the double slash for integer division, where the result is rounded to the nearest integer:

In [51]:
# Integer division operation expression

25 // 5

5

In [52]:
# Integer division operation expression

25 // 6

4

## <h3 id="exer_exp">Exercise: Expression</h3>

<p>Let's write an expression that calculates how many hours there are in 160 minutes:

In [53]:
# Write your code below. Don't forget to press Shift+Enter to execute the cell
160/60

2.6666666666666665

Double-click __here__ for the solution.

<!-- Your answer is below:
160/60
# Or
160//60
-->

<p>Python follows well accepted mathematical conventions when evaluating mathematical expressions. In the following example, Python adds 30 to the result of the multiplication (i.e., 120).

In [54]:
# Mathematical expression

30 + 2 * 60 // 10

42

<p>And just like mathematics, expressions enclosed in parentheses have priority. So the following multiplies 32 by 60.

In [55]:
# Mathematical expression

(30 + 2) * 60

1920

## <h3 id="var">Variables</h3>

<p>Just like with most programming languages, we can store values in <i>variables</i>, so we can use them later on. For example:</p>

In [57]:
# Store value into variable

x = 43 + 60 + 16 + 41
x

160

<p>To see the value of <code>x</code> in a Notebook, we can simply place it on the last line of a cell:</p>

In [62]:
# Print out the value in variable

x = 43 + 60 + 16 + 41
x

160

<p>We can also perform operations on <code>x</code> and save the result to a new variable:</p>

In [59]:
# Use another variable to store the result of the operation between variable and value

y = x / 60
y

2.6666666666666665

<p>If we save a value to an existing variable, the new value will overwrite the previous value:</p>

In [64]:
# Overwrite variable with new value

x = x / 60
print(x)

2.6666666666666665

In [65]:
x

2.6666666666666665

<p>It's a good practice to use meaningful variable names, so you and others can read the code and understand it more easily:</p>

In [66]:
# Name the variables meaningfully

total_min = 43 + 42 + 57 # Total length of albums in minutes
total_min

142

In [77]:
# Name the variables meaningfully

total_min = 43 + 42 + 57 # Total length of albums in minutes
total_min

142

In [78]:
float(total_min)

TypeError: ignored

In [80]:
a=2
a

2

In [83]:
print(float(a))

TypeError: ignored

In [67]:
# Name the variables meaningfully

total_hours = total_min / 60 # Total length of albums in hours
total_hours

2.3666666666666667

<p>In the cells above we added the length of three albums in minutes and stored it in <code>total_min</code>. We then divided it by 60 to calculate total length <code>total_hours</code> in hours. You can also do it all at once in a single expression, as long as you use parenthesis to add the albums length before you divide, as shown below.</p>

In [84]:
# Complicate expression

total_hours = (43 + 42 + 57) / 60  # Total hours in a single expression
total_hours

2.3666666666666667

<p>If you'd rather have total hours as an integer, you can of course replace the floating point division with integer division (i.e., <code>//</code>).</p>

## <h3 id="exer_exp_var">Exercise: Expression and Variables in Python</h3>

<p>What is the value of <code>x</code> where <code>x = 3 + 2 * 2</code></p>

In [ ]:
# Write your code below. Don't forget to press Shift+Enter to execute the cell

Double-click __here__ for the solution.

<!-- Your answer is below:
7
-->

<p>What is the value of <code>y</code> where <code>y = (3 + 2) * 2</code>?</p>

In [ ]:
# Write your code below. Don't forget to press Shift+Enter to execute the cell

Double-click __here__ for the solution.

<!-- Your answer is below:
10
-->

<p>What is the value of <code>z</code> where <code>z = x + y</code>?</p>

In [ ]:
# Write your code below. Don't forget to press Shift+Enter to execute the cell

Double-click __here__ for the solution.

<!-- Your answer is below:
17
-->

<hr>

## <h3 id="WeeklyExercise1">Weekly Exercise 1</h3>



Perbaiki script berikut sehingga tidak muncul error.

<pre>
panjang = 20,5
lebar = 25
tinggi = 10

keliling = 2*(panjang+lebar)
luas = panjang*/lebar
volum = panjang*lebar*tiggi

print("Panjang = " + 'panjang')
printl("Lebar = ' + lebar)
print('Tinggi = "  tinggi)
printl("Keliling = "  'kelling')
print("Volume = " + volume)
</pre>


## <h3 id="WeeklyExercise2">Weekly Exercise 2</h3>
Terdapat data mahasiswa sebagai berikut:
<p>
<a align="center">
    <img src="https://core-ruangguru.s3.amazonaws.com/assets/ruang_belajar/questions/q_9cagpe6808.PNG" width="300">
</a> </p>


Berdasarkan data di atas, buatlah sebuah program untuk menampilkan data-data berikut :
1. Rata-rata nilai Shafira pada kedua mata kuliah
2. Jumlah nilai Hanif dan Andi untuk semua mata kuliah
3. Rata-rata nilai Widya, Dhanar, Hikma dan Nedia pada masing-masing mata kuliah
3. Rata-rata nilai mata kuliah Kalkulus 1 untuk semua mahasiswa
4. Rata-rata nilai mata kuliah Metode Statistika untuk semua mahasiswa

Dengan ketentuan gunakan variabel agar memudahkan dalam menampilkan hasil

## <h3 id="WeeklyExercise1">Weekly Exercise 3</h3>



Diketahui Dwi adalah seorang karyawan pabrik swasta yang telah bekerja selama 10 tahun. Setiap hari Dwi bekerja selama 8 jam. Prosedur penerimaan honor dari perusahaan ditentukan dengan cara jumlah jam masuk dikali dengan Rp 30.000,-.

Buatlah sebuah program untuk menampilkan data berikut:
1. Gaji pada bulan Agustus jika Dwi tidak masuk kerja selama 3 hari, berapa gaji yang diterima oleh Dwi.
2. Apabila terdapat tunjangan bagi karyawan yang bekerja lebih dari 5 tahun sebesar 10% dari total gaji yang diterima setiap bulan, tentukan jumlah tunjangan yang diterima oleh Dwi pada bulan Agustus.
3. Apabila pada bulan Agustus Dwi mendapatkan tugas lembur selama 5 jam, tentukan gaji total yang diterima oleh Dwi pada bulan Agustus. (upah lembur : Rp 10.000,- per jam)

<hr>

<p>Copyright &copy; Prodi Teknologi Informasi -  Universitas Tidar.</p>